testname: QVIM  Subjective Evaluation
testId: default_example
bufferSize: 2048
stopOnErrors: true
showButtonPreviousPage: true
remoteService: service/write.php


pages:
    - type: generic
      id: first_page
      name: Querying by vocal imitation MUSHRA Test
      content: Thank you for being a part on our subjective evaluation to decide which team wins the Querying by vocal imitation challenge from the Audio Engineering Society (AES) AIMLA Conference 2025 !  You will rate 20 sound categories.  The objective of this test is that you will have different imitations and you will say which imitation sounds closer to the reference (real sound they're trying to imitate. )     
    - type: mushra
      id: trial1
      name: MUSHRA
      content: This training shows how to use our user interface. Please perform the underlined instructions to proceed with the training session. Reminder: In a MUSHRA listening test you are asked to rate the Basic Audio Quality (BAQ) of each condition.<br/>Basic Audio Quality is a single and global attribute that is used to judge any and all detected differences between the reference and the condition.
      showWaveform: true
      enableLooping: true 
      reference: configs/resources/audio/mono_ref.wav
      createAnchor35: true
      createAnchor70: true
      stimuli:
          C1: configs/resources/audio/mono_c1.wav
          C2: configs/resources/audio/mono_c2.wav
          C3: configs/resources/audio/mono_c3.wav
    - 
          - random
          - type: mushra
            id: trial_random_1
            name: Sound Category 1 - 
            content: Due to randomization, this page will be either the second MUSHRA page or the third MUSHRA page.
            enableLooping: true 
            reference: configs/resources/audio/mono_ref.wav
            createAnchor35: false
            createAnchor70: false
            stimuli:
                C1: configs/resources/audio/mono_c1.wav
                C2: configs/resources/audio/mono_c2.wav
                C3: configs/resources/audio/mono_c3.wav          
          - type: mushra
            id: trial_random_2
            name: Sound Category 2-
            content: Due to randomization, this page will be either the second MUSHRA page or the third MUSHRA page.
            enableLooping: true 
            reference: configs/resources/audio/mono_ref.wav
            createAnchor35: false
            createAnchor70: false
            stimuli:
                C1: configs/resources/audio/mono_c1.wav
                C2: configs/resources/audio/mono_c2.wav
                C3: configs/resources/audio/mono_c3.wav   
          - type: mushra
            id: trial_random_3
            name: Sound Category 3-
            content: Due to randomization, this page will be either the second MUSHRA page or the third MUSHRA page.
            enableLooping: true 
            reference: configs/resources/audio/mono_ref.wav
            createAnchor35: false
            createAnchor70: false
            stimuli:
                C1: configs/resources/audio/mono_c1.wav
                C2: configs/resources/audio/mono_c2.wav
                C3: configs/resources/audio/mono_c3.wav 
          - type: mushra
            id: trial_random_4
            name: Sound Category 4-
            content: Due to randomization, this page will be either the second MUSHRA page or the third MUSHRA page.
            enableLooping: true 
            reference: configs/resources/audio/mono_ref.wav
            createAnchor35: false
            createAnchor70: false
            stimuli:
                C1: configs/resources/audio/mono_c1.wav
                C2: configs/resources/audio/mono_c2.wav
                C3: configs/resources/audio/mono_c3.wav   
          - type: mushra
            id: trial_random_5
            name: Sound Category 5-
            content: Due to randomization, this page will be either the second MUSHRA page or the third MUSHRA page.
            enableLooping: true 
            reference: configs/resources/audio/mono_ref.wav
            createAnchor35: false
            createAnchor70: false
            stimuli:
                C1: configs/resources/audio/mono_c1.wav
                C2: configs/resources/audio/mono_c2.wav
                C3: configs/resources/audio/mono_c3.wav  
           - type: mushra
            id: trial_random_6
            name: Sound Category 6-
            content: Due to randomization, this page will be either the second MUSHRA page or the third MUSHRA page.
            enableLooping: true 
            reference: configs/resources/audio/mono_ref.wav
            createAnchor35: false
            createAnchor70: false
            stimuli:
                C1: configs/resources/audio/mono_c1.wav
                C2: configs/resources/audio/mono_c2.wav
                C3: configs/resources/audio/mono_c3.wav                   
    - type: finish
      name: Thank you
      content: Thank you for attending!
      showResults: true
      writeResults: true
      questionnaire:
          - type: text
            label: eMail
            name: email
          - type: number
            label: Age
            name: age
            min: 0
            max: 100
            default: 30
          - type: likert
            name: gender
            label: Gender
            response:
             - value: female
               label: Female
             - value: male
               label: Male
             - value: other
               label: Other
